# Generated by Django 3.2 on 2026-04-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20251102_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='external_source',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='external_source_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
