# Generated by Django 5.2.7 on 2026-04-27 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_promocode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_id_f21274_idx',
            old_fields=('id', 'slug'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='users',
            field=models.ManyToManyField(related_name='shop_clusters', to=settings.AUTH_USER_MODEL),
        ),
    ]
