# Generated by Django 5.2.7 on 2026-04-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_add_promo_discount_fields'),
        ('shop', '0016_rename_product_id_slug_shop_produc_id_f21274_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
    ]
